CREATE DATABASE escola_db;

CREATE TABLE alunos(
	id INT AUTO_INCREMENT PRIMARY KEY,
	Nome VARCHAR (80) NOT NULL,
	cpf CHAR (11) NOT NULL UNIQUE,
	cep CHAR (8),
	uf CHAR (2),
	rua VARCHAR (120),
	número INT,
	complemento VARCHAR (120),
	data_hora_criação TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	data_hora_atualização TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
